version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql@16/data
    networks:
      - local-net

volumes:
  postgres_data:

networks:
  local-net:
    driver: bridge
