version: "3"
services:
  calc-service:
    build:
      context: ./calc-service
      dockerfile: Dockerfile
    container_name: calc-service
    ports:
      - "3001:3001"
    networks:
      - local-net
      
  apollo-server:
    build:
      context: ./apollo-server
      dockerfile: Dockerfile
    container_name: apollo-server
    ports:
      - "4000:4000"
    networks:
      - local-net

  postgres:
    image: postgres:latest
    container_name: postgres
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql@16/data
    networks:
      - local-net

volumes:
  postgres_data:

networks:
  local-net:
    driver: bridge
